// Current placeholder based on references from thymoran-dreams.mjs
// Extend and export Actor class
export class ThymoranDreamsActor extends Actor {
    /** @override */
    prepareData () {
        // Prepare data for actor
        // Calling super.prepareData() executes in following order:
        // data reset (clear active effects), prepareBaseData(), prepareEmbeddedDocuments() (including active effects), prepareDerivedData()
        super.prepareData();
    }

    /** @override */
    prepareBaseData() {
        // Data modifications here occur before processing embedded docs or derived data
    }

    /**
     * @override
     * Augment actor source data with additional dynamic data not handled by DataModel
     * Data caluclated here should be available inside/outside of character sheets
     */
    prepareDerivedData() {
        const actorData = this;
        const flags = actorData.flags.thymorandreams || {};
    }

    /**
    * @override
    * Augment the actor's default getRollData() method by appending the data object
    * generated by the its DataModel's getRollData(), or null. This polymorphic
    * approach is useful when you have actors & items that share a parent Document,
    * but have slightly different data preparation needs.
    */
    getRollData() {
        return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
    }
}