// Current placeholder based on references from thymoran-dreams.mjs
// Extend and export Actor class
export class ThymoranDreamsActor extends Actor {
    /** @override */
    prepareData () {
        // Prepare data for actor
        // Calling super.prepareData() executes in following order:
        // data reset (clear active effects), prepareBaseData(), prepareEmbeddedDocuments() (including active effects), prepareDerivedData()
        super.prepareData();
    }

    /** @override */
    prepareBaseData() {
        // Data modifications here occur before processing embedded docs or derived data
        // From Wiki : if you need an Active Effect to modify a derived value, you can initialize or calculate the derived value in this step (such as an ability score modifier) so that the Active Effect can modify it later.
    }

    // MAY NEED TO ADD IN prepareEmbeddedDocuments() OVERRIDE IN ORDER TO ADD IN STATS FROM ITEMS / SKILLS / EFFECTS
    // From Wiki: this.prepareEmbeddedDocuments(); Prepare all embedded Documents within the parent Document, such as owned Items or Active Effects. Additionally, Active Effects are called in a submethod of this called this.applyActiveEffects(); which can be overridden.

    /**
     * @override
     * Augment actor source data with additional dynamic data not handled by DataModel
     * Data caluclated here should be available inside/outside of character sheets
     */
    prepareDerivedData() {
        const actorData = this;
        const flags = actorData.flags.thymorandreams || {};

        // CALCULATE SECONDARIES HERE? - AFTER PRIMARIES / ITEMS / EFFECTS ADDED ON
    }

    /**
    * @override
    * Augment the actor's default getRollData() method by appending the data object
    * generated by the its DataModel's getRollData(), or null. This polymorphic
    * approach is useful when you have actors & items that share a parent Document,
    * but have slightly different data preparation needs.
    */
    getRollData() {
        return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
    }
}